### ISSUE TITLE
PHP 7.3 Compatibility

### ISSUE THREAD

**Issue by igormatkovic** [shipperhq/module-shipper#71] opened 2019-10-16 17:19 UTC
Are there any plans regarding upgrading the code to be php 7.3 compatible.

Some minor errors are showing up when i try to install the package. 

For example:
https://github.com/shipperhq/module-shipper/blob/master/src/Model/Synchronizer.php#L217

https://www.php.net/manual/en/migration73.incompatible.php#migration73.incompatible.core.continue-targeting-switch

**Comment by edward-simpson** [comment] 2019-11-12 14:39
Is this going to be addressed?  We currently can't install this module because di compilation will not run due to the same issue as above on line 348

https://github.com/shipperhq/module-shipper/blob/master/src/Model/Synchronizer.php#L348

**Comment by ibraheemnabeelfauzi** [comment] 2019-11-13 23:18
Hi @edward-simpson & @igormatkovic, 

Many thanks for raising this, I was able to reproduce this and I'll flag with my lead engineer to look into. 

If you could also list all the steps you've taken to reproduce this then that will be very helpful. 

Thank you.

**Comment by wsajason** [comment] 2019-11-18 11:52
Hi. This has been resolved in 20.33.0

**Closed by wsajason** 2019-11-18 11:52 UTC
