### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by nickpiro** [shipperhq/module-shipper#62] opened 2019-02-13 14:01 UTC
We have tried multiple versions/releases of this module and have not had any success.

After first installing version  20.21.7 our Admin section was blank, our checkout blank, and shipping estimate on Cart page.

When we disabled the module, and were told by Magento to run: setup:di:compile, we received this error message:
Class 'ShipperHQ\Common\Helper\AbstractConfig' not found in /chroot/home/xxxx/xxxxx/html/app/code/ShipperHQ/Shipper/Helper/Config.php on line 44

After that, we moved onto completely removing the module's code since when we ran module:status, we showed the module was disabled. Then we ran into this issue.

When you load a product on the admin, you get this error once deleting the code from app/code:
<img width="762" alt="shipperhq-error" src="https://user-images.githubusercontent.com/36938969/52674869-e75b6280-2ef2-11e9-9781-83ea21ac90a5.png">

We have since tried every release from 20.21.5 to the latest .9.

Any ideas?

**Comment by wsajason** [comment] 2019-02-13 14:10
This is a duplicate of #61

**Closed by wsajason** 2019-02-13 14:10 UTC
Labels: duplicate
