### ISSUE TITLE
di:compile Issues

### ISSUE THREAD

**Issue by jksimoniii** [shipperhq/module-shipper#5] opened 2016-05-16 18:22 UTC
Running setup:di:compile throws the following errors although the compilation never actually fails. I haven't been able to identify a fix yet, but will report back if I find something.

```
ShipperHQ\Shipper\Helper\Data
		Incorrect dependency in class ShipperHQ\Shipper\Helper\Data in app/code/ShipperHQ/Shipper/Helper/Data.php \Magento\Framework\App\Config\ScopeConfigInterface already exists in context object


```

**Comment by wsagen** [comment] 2016-05-18 12:36
Thanks for highlighting although I'm not able to reproduce this locally. 

Have you done a composer update ? 
Are you using the standard or multi-tenant compile command?

**Comment by wsagen** [comment] 2016-05-30 01:31
Closing as not able to reproduce

**Closed by wsagen** 2016-05-30 01:31 UTC
